import { Questionnaire } from "@/types";

export const scl90: Questionnaire = {
    id: "scl90",
    title: "SCL-90 Symptom Checklist",
    description: "Comprehensive assessment of psychological health and psychiatric symptoms",
    tags: ["Self-assessment", "Mental Health", "Screening"],
    time: "10-15 minutes",
    details: {
        introduction: "The Symptom Checklist-90 (SCL-90) is one of the most widely used psychological screening instruments in the world. It is designed to assess a broad range of psychological problems and symptoms of psychopathology. The SCL-90 consists of 90 items covering areas from feelings, emotions, thinking, consciousness, behavior to lifestyle, interpersonal relationships, eating and sleeping patterns.",
        questionCount: "90 items",
        evaluationTime: "Usually 10-15 minutes",
        instructions: "Please read each item carefully and rate how much that problem has bothered you during the past week based on your actual situation. Choose the option that best describes your experience.",
        scoringMethod: [
            "Total Score: Sum of all item scores",
            "Positive Items: Number of items scored ≥2",
            "Positive Symptom Mean: Total positive score / Number of positive items",
            "Severity: Total score >160 or positive items >43 suggests psychological problems"
        ],
        dimensions: [
            { name: "Somatization", description: "Physical discomfort including cardiovascular, gastrointestinal, respiratory symptoms" },
            { name: "Obsessive-Compulsive", description: "Obsessive thoughts and compulsive behaviors" },
            { name: "Interpersonal Sensitivity", description: "Feelings of inadequacy and inferiority in interpersonal interactions" },
            { name: "Depression", description: "Low mood, loss of interest, feelings of hopelessness" },
            { name: "Anxiety", description: "Tension, nervousness, fear and related emotional experiences" },
            { name: "Hostility", description: "Anger, aggression, irritability and related emotions" },
            { name: "Phobic Anxiety", description: "Fear of specific places, people, or situations" },
            { name: "Paranoid Ideation", description: "Projective thinking, suspiciousness, hostility" },
            { name: "Psychoticism", description: "Hallucinations, delusions, thought disorders" },
            { name: "Additional Items", description: "Sleep, eating, and sexual problems" }
        ],
        notes: [
            "Assessment should be conducted in a quiet, undisturbed environment",
            "Respond honestly to reflect your true feelings without overthinking",
            "If scores are high, consider consulting a mental health professional"
        ],
        references: [
            {
                text: "Derogatis, L. R. (1977). SCL-90: Administration, scoring and procedure manual for the revised version. Clinical Psychometric Research.",
                url: "https://www.pearsonassessments.com"
            }
        ]
    },
    questions: [
        // Items 1-90 in English
        { id: 1, content: "Headaches" },
        { id: 2, content: "Nervousness or shakiness inside" },
        { id: 3, content: "Repeated unpleasant thoughts that won't leave your mind" },
        { id: 4, content: "Faintness or dizziness" },
        { id: 5, content: "Loss of sexual interest or pleasure" },
        { id: 6, content: "Feeling critical of others" },
        { id: 7, content: "The idea that someone else can control your thoughts" },
        { id: 8, content: "Feeling others are to blame for most of your troubles" },
        { id: 9, content: "Trouble remembering things" },
        { id: 10, content: "Worried about sloppiness or carelessness" },
        { id: 11, content: "Feeling easily annoyed or irritated" },
        { id: 12, content: "Pains in heart or chest" },
        { id: 13, content: "Feeling afraid in open spaces or on the streets" },
        { id: 14, content: "Feeling low in energy or slowed down" },
        { id: 15, content: "Thoughts of ending your life" },
        { id: 16, content: "Hearing voices that other people do not hear" },
        { id: 17, content: "Trembling" },
        { id: 18, content: "Feeling that most people cannot be trusted" },
        { id: 19, content: "Poor appetite" },
        { id: 20, content: "Crying easily" },
        { id: 21, content: "Feeling shy or uneasy with the opposite sex" },
        { id: 22, content: "Feelings of being trapped or caught" },
        { id: 23, content: "Suddenly scared for no reason" },
        { id: 24, content: "Temper outbursts that you could not control" },
        { id: 25, content: "Feeling afraid to go out of your house alone" },
        { id: 26, content: "Blaming yourself for things" },
        { id: 27, content: "Pains in lower back" },
        { id: 28, content: "Feeling blocked in getting things done" },
        { id: 29, content: "Feeling lonely" },
        { id: 30, content: "Feeling blue" },
        { id: 31, content: "Worrying too much about things" },
        { id: 32, content: "Feeling no interest in things" },
        { id: 33, content: "Feeling fearful" },
        { id: 34, content: "Your feelings being easily hurt" },
        { id: 35, content: "Other people being aware of your private thoughts" },
        { id: 36, content: "Feeling others do not understand you or are unsympathetic" },
        { id: 37, content: "Feeling that people are unfriendly or dislike you" },
        { id: 38, content: "Having to do things very slowly to insure correctness" },
        { id: 39, content: "Heart pounding or racing" },
        { id: 40, content: "Nausea or upset stomach" },
        { id: 41, content: "Feeling inferior to others" },
        { id: 42, content: "Soreness of your muscles" },
        { id: 43, content: "Feeling that you are watched or talked about by others" },
        { id: 44, content: "Trouble falling asleep" },
        { id: 45, content: "Having to check and double-check what you do" },
        { id: 46, content: "Difficulty making decisions" },
        { id: 47, content: "Feeling afraid to travel on buses, subways, or trains" },
        { id: 48, content: "Trouble getting your breath" },
        { id: 49, content: "Hot or cold spells" },
        { id: 50, content: "Having to avoid certain things, places, or activities because they frighten you" },
        { id: 51, content: "Your mind going blank" },
        { id: 52, content: "Numbness or tingling in parts of your body" },
        { id: 53, content: "A lump in your throat" },
        { id: 54, content: "Feeling hopeless about the future" },
        { id: 55, content: "Trouble concentrating" },
        { id: 56, content: "Feeling weak in parts of your body" },
        { id: 57, content: "Feeling tense or keyed up" },
        { id: 58, content: "Heavy feelings in your arms or legs" },
        { id: 59, content: "Thoughts of death or dying" },
        { id: 60, content: "Overeating" },
        { id: 61, content: "Feeling uneasy when people are watching or talking about you" },
        { id: 62, content: "Having thoughts that are not your own" },
        { id: 63, content: "Having urges to beat, injure, or harm someone" },
        { id: 64, content: "Awakening in the early morning" },
        { id: 65, content: "Having to repeat the same actions such as touching, counting, or washing" },
        { id: 66, content: "Sleep that is restless or disturbed" },
        { id: 67, content: "Having urges to break or smash things" },
        { id: 68, content: "Having ideas or beliefs that others do not share" },
        { id: 69, content: "Feeling very self-conscious with others" },
        { id: 70, content: "Feeling uneasy in crowds, such as shopping or at a movie" },
        { id: 71, content: "Feeling everything is an effort" },
        { id: 72, content: "Spells of terror or panic" },
        { id: 73, content: "Feeling uncomfortable about eating or drinking in public" },
        { id: 74, content: "Getting into frequent arguments" },
        { id: 75, content: "Feeling nervous when you are left alone" },
        { id: 76, content: "Others not giving you proper credit for your achievements" },
        { id: 77, content: "Feeling lonely even when you are with people" },
        { id: 78, content: "Feeling so restless you couldn't sit still" },
        { id: 79, content: "Feelings of worthlessness" },
        { id: 80, content: "The feeling that familiar things are strange or unreal" },
        { id: 81, content: "Shouting or throwing things" },
        { id: 82, content: "Feeling afraid you will faint in public" },
        { id: 83, content: "Feeling that people will take advantage of you if you let them" },
        { id: 84, content: "Having thoughts about sex that bother you a lot" },
        { id: 85, content: "The idea that you should be punished for your sins" },
        { id: 86, content: "Feeling pushed to get things done" },
        { id: 87, content: "The idea that something serious is wrong with your body" },
        { id: 88, content: "Never feeling close to another person" },
        { id: 89, content: "Feelings of guilt" },
        { id: 90, content: "The idea that something is wrong with your mind" }
    ],
    renderOptions: () => [
        { id: 1, content: "Not at all", value: "1" },
        { id: 2, content: "A little bit", value: "2" },
        { id: 3, content: "Moderately", value: "3" },
        { id: 4, content: "Quite a bit", value: "4" },
        { id: 5, content: "Extremely", value: "5" }
    ]
};