import { Questionnaire } from "@/types";

export const scl90: Questionnaire = {
    id: "scl90",
    title: "SCL-90症状自评量表",
    description: "综合评估心理健康状况和精神症状",
    tags: ["症状自评", "心理健康", "筛查"],
    time: "10-15分钟",
    details: {
        introduction: "症状自评量表SCL-90是世界上最著名的心理健康测试量表之一，是当前使用最为广泛的精神障碍和心理疾病门诊检查量表，适用于评估一个人的心理健康状况。该量表包含90个项目，从感觉、情绪、思维、意识、行为直至生活习惯、人际关系、饮食睡眠等多个方面评估心理健康程度。",
        questionCount: "90个项目",
        evaluationTime: "通常为10-15分钟",
        instructions: "请仔细阅读每一个项目，根据您最近一周的实际情况进行评分。选择最符合您情况的选项。",
        scoringMethod: [
            "总分：将所有项目得分相加",
            "阳性项目数：得分≥2分的项目数",
            "阳性症状均分：阳性项目总分/阳性项目数",
            "严重程度：总分>160分或阳性项目数>43个提示存在心理问题"
        ],
        dimensions: [
            { name: "躯体化", description: "身体不适感，包括心血管、胃肠道、呼吸系统等症状" },
            { name: "强迫症状", description: "强迫思维和强迫行为等症状" },
            { name: "人际关系敏感", description: "人际交往中的自卑感、心神不安等" },
            { name: "抑郁", description: "情绪低落、兴趣丧失、绝望感等" },
            { name: "焦虑", description: "紧张、心烦、恐惧等情绪体验" },
            { name: "敌对", description: "愤怒、攻击性、烦躁等情绪" },
            { name: "恐怖", description: "对特定场所、人群、情境的恐惧" },
            { name: "偏执", description: "投射性思维、猜疑、敌意等" },
            { name: "精神病性", description: "幻觉、妄想、思维障碍等" },
            { name: "其他", description: "睡眠、饮食、性方面的问题" }
        ],
        notes: [
            "评估应在安静、不受干扰的环境中进行",
            "需要真实反映自己的感受，不要过分思考",
            "如果得分较高，建议咨询专业心理医生"
        ],
        references: [
            {
                text: "王征宇, 张明园, 等. 症状自评量表SCL-90的信度和效度研究. 上海精神医学, 1984, 2(2): 68-70.",
                url: "https://www.cnki.net"
            }
        ]
    },
    questions: [
        // Somatization (1-12)
        { id: 1, content: "头痛" },
        { id: 2, content: "神经过敏，心中不踏实" },
        { id: 3, content: "头脑中有不必要的想法或字句盘旋" },
        { id: 4, content: "头昏或昏倒" },
        { id: 5, content: "对异性的兴趣减退" },
        { id: 6, content: "对旁人责备求全" },
        { id: 7, content: "感到别人能控制您的思想" },
        { id: 8, content: "责怪别人制造麻烦" },
        { id: 9, content: "忘记性大" },
        { id: 10, content: "担心自己的衣着整齐和仪表端正" },
        { id: 11, content: "容易烦恼和激动" },
        { id: 12, content: "胸痛" },
        { id: 13, content: "害怕空旷的场所或街道" },
        { id: 14, content: "感到自己的精力下降，活动减慢" },
        { id: 15, content: "想结束自己的生命" },
        { id: 16, content: "听到旁人听不到的声音" },
        { id: 17, content: "发抖" },
        { id: 18, content: "感到大多数人都不可信任" },
        { id: 19, content: "胃口不好" },
        { id: 20, content: "容易哭泣" },
        { id: 21, content: "同异性相处时感到害羞不自在" },
        { id: 22, content: "感到受骗，中了圈套或有人想抓住您" },
        { id: 23, content: "无缘无故地突然感到害怕" },
        { id: 24, content: "自己不能控制地大发脾气" },
        { id: 25, content: "怕单独出门" },
        { id: 26, content: "经常责怪自己" },
        { id: 27, content: "腰痛" },
        { id: 28, content: "感到难以完成任务" },
        { id: 29, content: "感到孤独" },
        { id: 30, content: "感到苦闷" },
        { id: 31, content: "过分担忧" },
        { id: 32, content: "对事物不感兴趣" },
        { id: 33, content: "感到害怕" },
        { id: 34, content: "您的感情容易受到伤害" },
        { id: 35, content: "旁人能知道您的私下想法" },
        { id: 36, content: "感到别人不理解您或不同情您" },
        { id: 37, content: "感到人们对您不友好，不喜欢您" },
        { id: 38, content: "做事必须做得很慢以保证做得正确" },
        { id: 39, content: "心跳得很厉害" },
        { id: 40, content: "恶心或胃部不舒服" },
        { id: 41, content: "感到比不上他人" },
        { id: 42, content: "肌肉酸痛" },
        { id: 43, content: "感到有人在监视您、谈论您" },
        { id: 44, content: "难以入睡" },
        { id: 45, content: "做事必须反复检查" },
        { id: 46, content: "难以作出决定" },
        { id: 47, content: "怕乘电车、公共汽车、地铁或火车" },
        { id: 48, content: "呼吸有困难" },
        { id: 49, content: "一阵阵发冷或发热" },
        { id: 50, content: "因为感到害怕而避开某些东西、场所或活动" },
        { id: 51, content: "脑子变空了" },
        { id: 52, content: "身体的某一部分麻木或刺痛" },
        { id: 53, content: "喉咙有梗塞感" },
        { id: 54, content: "感到前途没有希望" },
        { id: 55, content: "不能集中注意力" },
        { id: 56, content: "感到身体的某一部分软弱无力" },
        { id: 57, content: "感到紧张或心神不定" },
        { id: 58, content: "感到手或脚发重" },
        { id: 59, content: "想到有关死亡的事" },
        { id: 60, content: "吃得太多" },
        { id: 61, content: "当别人看着您或谈论您时感到不自在" },
        { id: 62, content: "有一些不属于您自己的想法" },
        { id: 63, content: "有想打人或伤害他人的冲动" },
        { id: 64, content: "醒得太早" },
        { id: 65, content: "必须反复洗手、点数或触摸某些东西" },
        { id: 66, content: "睡得不稳不深" },
        { id: 67, content: "有想摔坏或破坏东西的冲动" },
        { id: 68, content: "有一些别人没有的想法" },
        { id: 69, content: "感到对别人神经过敏" },
        { id: 70, content: "在商店或电影院等人多的地方感到不自在" },
        { id: 71, content: "感到任何事情都很困难" },
        { id: 72, content: "一阵阵恐惧或惊恐" },
        { id: 73, content: "感到在公共场所吃东西很不舒服" },
        { id: 74, content: "经常与人争论" },
        { id: 75, content: "单独一人时神经很紧张" },
        { id: 76, content: "别人对您的成绩没有做出恰当的评价" },
        { id: 77, content: "即使和别人在一起也感到孤独" },
        { id: 78, content: "感到坐立不安心神不定" },
        { id: 79, content: "感到自己没有什么价值" },
        { id: 80, content: "感到熟悉的东西变成陌生或不象是真的" },
        { id: 81, content: "大叫或摔东西" },
        { id: 82, content: "害怕会在公共场所昏倒" },
        { id: 83, content: "感到别人想占您的便宜" },
        { id: 84, content: "为一些有关性的想法而苦恼" },
        { id: 85, content: "您认为应该因为自己的过错而受到惩罚" },
        { id: 86, content: "感到要很快把事情做完" },
        { id: 87, content: "感到自己的身体有严重问题" },
        { id: 88, content: "从未感到和其他人很亲近" },
        { id: 89, content: "感到有罪恶感" },
        { id: 90, content: "感到自己的脑子有毛病" }
    ],
    renderOptions: () => [
        { id: 1, content: "没有", value: "1" },
        { id: 2, content: "很轻", value: "2" },
        { id: 3, content: "中等", value: "3" },
        { id: 4, content: "偏重", value: "4" },
        { id: 5, content: "严重", value: "5" }
    ]
};